# Generated by Django 5.0.7 on 2025-07-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_permissions_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'مشاهده\u200cکننده'), ('editor', 'ویرایشگر'), ('admin', 'مدیر سیستم')], default='guest', max_length=50),
        ),
    ]
