# Generated by Django 5.0.7 on 2025-07-15 23:18

import docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=docs.models.upload_to)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('s', 'Coin'), ('m', 'Magazine'), ('st', 'Student')], default='s', max_length=2)),
                ('suffix', models.CharField(max_length=80)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
