# Generated by Django 5.0.7 on 2025-07-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_trash',
            field=models.BooleanField(default=False),
        ),
    ]
